name: Compile Custom OpenCV

on:
  workflow_dispatch:

jobs:
  build-custom-opencv:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools platforms;android-21 ndk;27.1.12297006'

      - name: Clone OpenCV mobile Source Code
        run: |
          wget -q https://github.com/nihui/opencv-mobile/releases/download/v34/opencv-mobile-4.12.0.zip
          unzip -q opencv-mobile-4.12.0.zip

      - name: Replace UMat with Mat everywhere
        run: |
          cd opencv-mobile-4.12.0
          find . -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) \
            -exec sed -i 's/\bUMat\b/Mat/g' {} +

      - name: Build custom OpenCV-build
        run: |
          cd opencv-mobile-4.12.0
          mkdir build
          cd build

          cmake \
            -DCMAKE_POLICY_DEFAULT_CMP0057=NEW \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=False \
            -DANDROID_PLATFORM=android-21 \
            -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
            -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install" \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_STL=c++_shared \
            -DCMAKE_C_FLAGS_RELEASE="-Os -fdata-sections -ffunction-sections" \
            -DCMAKE_CXX_FLAGS_RELEASE="-Os -fdata-sections -ffunction-sections"  \
            -DANDROID_ABI="arm64-v8a" \
            `cat "$GITHUB_WORKSPACE/.github/opencv/options.txt"` \
            -DBUILD_opencv_world=OFF \
            -DOPENCV_DISABLE_FILESYSTEM_SUPPORT=ON \
            -DOPENCV_EXTRA_FLAGS="-mno-outline-atomics" \
            ..
          make -j4
          make install

      - name: Verify OpenCV Static Libraries
        run: |
          echo "=========================================================="
          echo "             OPENCV STATIC LIBRARIES"
          echo "=========================================================="

          find install/ \
            -type f \
            -name "*.a" \
            -exec ls -lh {} +

          echo "=========================================================="

      - name: Create custom opencv build release zip archive
        run: |
          cd install
          zip -r $GITHUB_WORKSPACE/opencv-mobile-4.12.0-android-arm64.zip . \
            -x "**/build/*"

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: opencv-botsort-4.12.0
          name: OpenCV 4.12.0 custom Android build
          files: ${{ github.workspace }}/opencv-mobile-4.12.0-android-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
